# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chull.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hull.proto\x12\x05proto\"\x1e\n\x06Points\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"q\n\x0c\x43hullRequest\x12\t\n\x01n\x18\x01 \x01(\r\x12\x1d\n\x06points\x18\x02 \x03(\x0b\x32\r.proto.Points\x12\x0f\n\x07getArea\x18\x03 \x01(\x08\x12\x11\n\tgetPoints\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"S\n\rChullResponse\x12\x11\n\x04\x61rea\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\t\n\x01n\x18\x02 \x01(\r\x12\x1b\n\x04hull\x18\x03 \x03(\x0b\x32\r.proto.PointsB\x07\n\x05_area2O\n\x10\x43onvexHullFinder\x12;\n\x0e\x46indConvexHull\x12\x13.proto.ChullRequest\x1a\x14.proto.ChullResponseb\x06proto3')



_POINTS = DESCRIPTOR.message_types_by_name['Points']
_CHULLREQUEST = DESCRIPTOR.message_types_by_name['ChullRequest']
_CHULLRESPONSE = DESCRIPTOR.message_types_by_name['ChullResponse']
Points = _reflection.GeneratedProtocolMessageType('Points', (_message.Message,), {
  'DESCRIPTOR' : _POINTS,
  '__module__' : 'chull_pb2'
  # @@protoc_insertion_point(class_scope:proto.Points)
  })
_sym_db.RegisterMessage(Points)

ChullRequest = _reflection.GeneratedProtocolMessageType('ChullRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHULLREQUEST,
  '__module__' : 'chull_pb2'
  # @@protoc_insertion_point(class_scope:proto.ChullRequest)
  })
_sym_db.RegisterMessage(ChullRequest)

ChullResponse = _reflection.GeneratedProtocolMessageType('ChullResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHULLRESPONSE,
  '__module__' : 'chull_pb2'
  # @@protoc_insertion_point(class_scope:proto.ChullResponse)
  })
_sym_db.RegisterMessage(ChullResponse)

_CONVEXHULLFINDER = DESCRIPTOR.services_by_name['ConvexHullFinder']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTS._serialized_start=22
  _POINTS._serialized_end=52
  _CHULLREQUEST._serialized_start=54
  _CHULLREQUEST._serialized_end=167
  _CHULLRESPONSE._serialized_start=169
  _CHULLRESPONSE._serialized_end=252
  _CONVEXHULLFINDER._serialized_start=254
  _CONVEXHULLFINDER._serialized_end=333
# @@protoc_insertion_point(module_scope)
